FROM python:3.12.9-slim
WORKDIR /app
COPY . .
RUN python -m venv /app/CovitVenv \
&& /app/CovitVenv/bin/pip install --upgrade pip \
&& /app/CovitVenv/bin/pip install --no-cache-dir -r requirements.txt

ENV PATH = "/app/NumVCovitVenvenv/bin:$PATH"